//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Column.java
//  @ Date : 2015/5/9
//  @ Author : shanlin
//
//
package com.shanlin.demo.codegen.model;

public class Column {
    private String columnName;
    /**
     * 对应的java.sql.Types类型
     */
    private int dataType;
    private String dataTypeName;
    private String attrName;
    private String attrNameFirstUpper;
    private String desc;
    
	public String getColumnName() {
		return columnName;
	}
	public void setColumnName(String columnName) {
		this.columnName = columnName;
		String[] names = columnName.toLowerCase().split("_");
		
		for (int i=0; i<names.length; i++) {
			this.attrNameFirstUpper = this.attrNameFirstUpper+
					names[i].substring(0, 1).toUpperCase()+
					names[i].substring(1);
		}
		
		this.attrName = this.attrNameFirstUpper.substring(0, 1)
				.toLowerCase() + this.attrNameFirstUpper.substring(1);
	}
	public String getAttrName() {
		return this.attrName;
	}
	public String getDataTypeName() {
		return dataTypeName;
	}
	public void setDataTypeName(String dataTypeName) {
		this.dataTypeName = dataTypeName;
	}
	public int getDataType() {
		return dataType;
	}
	public void setDataType(int dataType) {
		this.dataType = dataType;
	}
	public String getDesc() {
		return desc;
	}
	public void setDesc(String desc) {
		this.desc = desc;
	}
	public String getAttrNameFirstUpper() {
		return attrNameFirstUpper;
	}
}
