//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Table.java
//  @ Date : 2015/5/9
//  @ Author : shanlin
//
//
package com.shanlin.demo.codegen.model;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.shanlin.demo.codegen.properties.PropertisBudle;
import com.shanlin.demo.codegen.utils.StringUtils;

public class Table {
    private String tableName;
    private String tableClassName="";
    private String classNameFirstLower="";
	private String createTime;
    public List<Column> columns = new ArrayList<Column>();
    
	public String getTableName() {
		return tableName;
	}
	
	public void setTableName(String tableName) {
		this.tableName = tableName.toLowerCase();
		String[] names = tableName.toLowerCase().replaceFirst(PropertisBudle.DB_TABLE_PREFIX, "").split("_");
		
		for (int i=0; i<names.length; i++) {
			this.tableClassName = this.tableClassName+
					names[i].substring(0, 1).toUpperCase()+
					names[i].substring(1);
		}
		
		this.classNameFirstLower = StringUtils.toLowwerFirstChar(tableClassName);
	}
	public String getTableClassName() {
		return tableClassName;
	}
	public List<Column> getColumns() {
		return columns;
	}
	public void setColumns(List<Column> columns) {
		this.columns = columns;
	}

	public String getClassNameFirstLower() {
		return classNameFirstLower;
	}

    public String getCreateTime() {
        return new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(new Date());
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
}
