//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Generator.java
//  @ Date : 2015/5/9
//  @ Author : shanlin
//
//
package com.shanlin.demo.codegen.generator;


public class Generator {
	public static void main(String[] args){
		GeneratorFacecade facecade = new GeneratorFacecade();
		facecade.gen();
	}
}
