//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DataBaseHandler.java
//  @ Date : 2015/5/9
//  @ Author : shanlin
//
//
package com.shanlin.demo.codegen.handler;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.shanlin.demo.codegen.model.Column;
import com.shanlin.demo.codegen.model.Table;
import com.shanlin.demo.codegen.properties.PropertisBudle;

public class DataBaseHandler {
	private static final String DB = "jdbc://" + PropertisBudle.DB_TYPE + "://"
			+ PropertisBudle.DB_URL + ":" + PropertisBudle.DB_PORT + "/"
			+ PropertisBudle.DB_SCHEAME;
	private static Connection connection;
	
	static{
		try {
			Class.forName(PropertisBudle.DB_DRIVER_CLASS);
			connection = DriverManager.getConnection(DB, PropertisBudle.DB_USERNAME, PropertisBudle.DB_PASSWORD);
		} catch (SQLException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
	}
	
	public static List<Table> getAllModel(){
		List<Table> tables = new ArrayList<Table>();
		
		try {
			Map<String, Table>  tableMap = getAllTables();
			tables = getAllColumnsForTable(tableMap);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return tables;
	}
	
	private static Map<String, Table> getAllTables() throws SQLException{
		DatabaseMetaData metaData = connection.getMetaData();
		// 获取scheame下的所有表
		ResultSet tableSet = metaData.getTables(null, PropertisBudle.DB_SCHEAME, "%", new String[]{"TABLE"});
		
		Map<String, Table> tables = new HashMap<String, Table>();
		Table table = null;
		while (tableSet.next()) {
			table = new Table();
			table.setTableName(tableSet.getString("TABLE_NAME"));
			
			tables.put(tableSet.getString("TABLE_NAME"), table);
		}
		
		return tables;
	}
	
	
	private static List<Table> getAllColumnsForTable(Map<String, Table> tables) throws SQLException{
		DatabaseMetaData metaData = connection.getMetaData();
		ResultSet rs = metaData.getColumns(null, PropertisBudle.DB_SCHEAME, "%", "%");
		
		Table table = null;
		Column column = null;
		while (rs.next()) {
			table = tables.get(rs.getString("TABLE_NAME"));
			column = new Column();
			column.setColumnName(rs.getString("COLUMN_NAME"));
			column.setDataType(rs.getInt("DATA_TYPE"));
			column.setDataTypeName(rs.getString("TYPE_NAME"));
			column.setDesc(rs.getString("REMARKS"));
			
			table.getColumns().add(column);
		}
		
		return new ArrayList<Table>(tables.values());
	}
	
	public static void colse() {
		try {
			if (connection != null) {
				connection.close();
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}
