//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FreeMarkHandler.java
//  @ Date : 2015/5/9
//  @ Author : shanlin
//
//
package com.shanlin.demo.codegen.handler;

import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.StringWriter;
import java.io.Writer;
import java.util.Map;

import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.Version;


public class FreeMarkerParser {
    private static Configuration configuration = null;
    private static Template template = null;
    
    static{
        configuration = new Configuration(new Version("1.0"));
        configuration.setAutoFlush(true);
        configuration.setClassicCompatible(true);
    }
    
    /**
     * 功能描述: <br>
     *
     * @param javaTemplate
     * @return the string that was parsed 
     */
    public static String parse(String templatePath, Map<String, Object> model){
        Writer out = null;
        Reader reader = null;
        try {
            out = new StringWriter();
            
            reader = new InputStreamReader(FreeMarkerParser.class.getResourceAsStream(templatePath), "utf-8");
            template = new Template(templatePath, reader, configuration);
            template.process(model, out);
            
            return out.toString();
        } catch (Exception e) {
        	e.printStackTrace();
        }finally{
            try {
                if (out !=null) {
                    out.close();
                }
                if (reader != null) {
					reader.close();
				}
            } catch (IOException e) {
            	e.printStackTrace();
            }
        }
        
        return null;
    }
}
