//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Generator.java
//  @ Date : 2015/5/9
//  @ Author : shanlin
//
//
package com.shanlin.demo.codegen.handler;


public class Generator {
}
