//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PropertisBudle.java
//  @ Date : 2015/5/9
//  @ Author : shanlin
//
//
package com.shanlin.demo.codegen.properties;


public class PropertisBudle extends NLS{
	public static String DB_DRIVER_CLASS;
	public static String DB_TYPE;
	public static String DB_URL;
	public static String DB_PORT;
	public static String DB_SCHEAME;
	public static String DB_USERNAME;
	public static String DB_PASSWORD;
	
    public static void init() {
    	NLS.initializeMessages("com.shanlin.demo.codegen.properties.config", PropertisBudle.class);
    }
}
