//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PropertisBudle.java
//  @ Date : 2015/5/9
//  @ Author : shanlin
//
//
package com.shanlin.demo.codegen.properties;


public class PropertisBudle extends NLS{
	/**
	 * 数据库路径
	 */
	public static String DB_DRIVER_CLASS;
	public static String DB_URL;
	public static String DB_SCHEAME;
	public static String DB_USERNAME;
	public static String DB_PASSWORD;
	public static String DB_TABLE_PREFIX;
	public static String DB_COLUMN_PREFIX;
	/**
	 * freemaker模板路径
	 */
	public static String FREEMARKER_TEMPLATE_ENTITY;
	/**
	 * 包路径
	 */
	public static String PACKAGE_ENTITY;
	
	
    static{
    	NLS.initializeMessages("com.shanlin.demo.codegen.properties.config", PropertisBudle.class);
    }
}
